◊(require racket/file racket/system)
◊(define (render-pdf path)
   (define-values (_dir filename _) (split-path path))
   (define doc-name
     (path->string (path-replace-extension (path-replace-extension filename "") "")))
   (system (format "raco pollen render ~a.ctx" doc-name))
   (define pdf-filename (format "~a-tmp.pdf" doc-name))
   (define ctx-command (format "context --purgeall --result=~a ~a.ctx" pdf-filename doc-name))
   (displayln ctx-command)
   (system ctx-command)
   (define pdf-bytes (file->bytes pdf-filename))
   (delete-file pdf-filename)
   pdf-bytes)
◊(render-pdf (select 'here-path metas))
